name: Push to Main

on:
  push:
    branches:
      - main

jobs:
  pull_request:
    name: Create Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run the action
        uses: devops-infra/action-pull-request@v0.5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: main
          target_branch: release/MAPL-v3
          label: automatic,MAPL3,Skip Changelog
          template: .github/PULL_REQUEST_TEMPLATE/auto_pr_to_mapl3.md
          get_diff: true
          assignee: ${{ github.actor }}
          old_string: "<!-- Write your description here -->"
          new_string: ${{ github.event.commits[0].message }}
          title: Auto PR - main → MAPL-v3 - ${{ github.event.commits[0].message }}

